# -*- coding: utf-8 -*-
"""R_Prog_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CcRKOoRygNNh1lBcugoksTFuZlzeG47P

Name: Ketki Gaikwad

Roll no.:23012A0060

Assignment 1
"""

# Commented out IPython magic to ensure Python compatibility.
# Run this Python cell first
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(ggplot2)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# list.files()

# Commented out IPython magic to ensure Python compatibility.
# %%R
# system("unzip -o beijing+multi+site+air+quality+data.zip -d air_quality")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# list.files("air_quality", recursive = TRUE)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# system("unzip -o air_quality/PRSA2017_Data_20130301-20170228.zip -d air_quality/PRSA2017")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# list.files("air_quality/PRSA2017")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# list.files("air_quality/PRSA2017/PRSA_Data_20130301-20170228")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# class(air_data)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# exists("air_data")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# air_data <- read.csv(
#   "air_quality/PRSA2017/PRSA_Data_20130301-20170228/PRSA_Data_Aotizhongxin_20130301-20170228.csv",
#   stringsAsFactors = FALSE
# )
# 
# print(dim(air_data))
# head(air_data)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# str(air_data)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# head(air_data)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# str(air_data)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# cat("Rows :", nrow(air_data), "\n")
# cat("Columns :", ncol(air_data), "\n")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# any(is.na(air_data))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# temperature <- c(28,30,NA,32)
# 
# missing_object <- NULL
# 
# undefined_value <- 0/0
# 
# cat("NA Example\n")
# print(temperature)
# print(is.na(temperature))
# 
# cat("\nNULL Example\n")
# print(missing_object)
# print(is.null(missing_object))
# 
# cat("\nNaN Example\n")
# print(undefined_value)
# print(is.nan(undefined_value))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# missing_summary <- function(df, variables){
# 
#   summary_table <- data.frame(
#     Variable = character(),
#     Total_Records = integer(),
#     Missing_Values = integer(),
#     Missing_Percentage = numeric(),
#     stringsAsFactors = FALSE
#   )
# 
#   for(var in variables){
# 
#     total_records <- nrow(df)
# 
#     missing_values <- sum(is.na(df[[var]]))
# 
#     missing_percentage <- round((missing_values/total_records)*100,2)
# 
#     summary_table <- rbind(
#       summary_table,
#       data.frame(
#         Variable = var,
#         Total_Records = total_records,
#         Missing_Values = missing_values,
#         Missing_Percentage = missing_percentage
#       )
#     )
# 
#     if(missing_percentage > 20){
#       warning(paste(var, "contains more than 20% missing values"))
#     }
# 
#   }
# 
#   return(summary_table)
# 
# }

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# selected_variables <- c(
#   "PM2.5",
#   "PM10",
#   "SO2",
#   "NO2",
#   "TEMP",
#   "WSPM",
#   "wd"
# )
# 
# summary_before <- missing_summary(air_data, selected_variables)
# 
# print(summary_before)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# summary_before <- missing_summary(air_data, selected_variables)
# 
# print(summary_before)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# air_data$pollution_ratio <- air_data$PM2.5 / air_data$PM10

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# cat("NA values:", sum(is.na(air_data$pollution_ratio)), "\n")
# cat("NaN values:", sum(is.nan(air_data$pollution_ratio)), "\n")
# cat("Infinite values:", sum(is.infinite(air_data$pollution_ratio)), "\n")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# air_data$pollution_ratio[
#   is.nan(air_data$pollution_ratio) |
#   is.infinite(air_data$pollution_ratio)
# ] <- NA

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# cat("NA values:", sum(is.na(air_data$pollution_ratio)), "\n")
# cat("NaN values:", sum(is.nan(air_data$pollution_ratio)), "\n")
# cat("Infinite values:", sum(is.infinite(air_data$pollution_ratio)), "\n")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# numeric_variables <- c(
#   "PM2.5",
#   "PM10",
#   "SO2",
#   "NO2",
#   "TEMP",
#   "WSPM"
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# before_missing <- c()
# after_missing <- c()
# median_used <- c()
# 
# for(var in numeric_variables){
# 
#   if(var %in% names(air_data)){
# 
#     before <- sum(is.na(air_data[[var]]))
# 
#     med <- median(air_data[[var]], na.rm = TRUE)
# 
#     air_data[[var]][is.na(air_data[[var]])] <- med
# 
#     after <- sum(is.na(air_data[[var]]))
# 
#     before_missing <- c(before_missing, before)
#     after_missing <- c(after_missing, after)
#     median_used <- c(median_used, med)
# 
#     cat("\n----------------------------------\n")
#     cat("Variable :", var, "\n")
#     cat("Missing Before :", before, "\n")
#     cat("Median Used :", med, "\n")
#     cat("Missing After :", after, "\n")
#   }
# }

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# numeric_comparison <- data.frame(
#   Variable = numeric_variables,
#   Missing_Before = before_missing,
#   Missing_After = after_missing,
#   Median_Used = median_used
# )
# 
# print(numeric_comparison)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# calculate_mode <- function(x){
# 
#   x <- x[!is.na(x)]   # Remove NA values
# 
#   unique_values <- unique(x)
# 
#   mode_value <- unique_values[
#     which.max(tabulate(match(x, unique_values)))
#   ]
# 
#   return(mode_value)
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# before_wd <- sum(is.na(air_data$wd))
# 
# cat("Missing values in wd before replacement:", before_wd, "\n")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# mode_wd <- calculate_mode(air_data$wd)
# 
# cat("Mode of wd:", mode_wd, "\n")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# air_data$wd[is.na(air_data$wd)] <- mode_wd

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# after_wd <- sum(is.na(air_data$wd))
# 
# cat("Missing values in wd after replacement:", after_wd, "\n")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# clean_variable <- function(df, variable_name){
# 
#   tryCatch({
# 
#     # Check if variable exists
#     if(!(variable_name %in% names(df))){
#       stop("Variable does not exist.")
#     }
# 
#     # Check if variable is numeric
#     if(!is.numeric(df[[variable_name]])){
#       stop("Variable is not numerical.")
#     }
# 
#     # Check if all values are missing
#     if(all(is.na(df[[variable_name]]))){
#       stop("Variable contains only missing values.")
#     }
# 
#     # Calculate median
#     med <- median(df[[variable_name]], na.rm = TRUE)
# 
#     if(is.na(med)){
#       stop("Median cannot be calculated.")
#     }
# 
#     # Replace missing values
#     df[[variable_name]][is.na(df[[variable_name]])] <- med
# 
#     cat(variable_name, "cleaned successfully.\n")
# 
#    return(df)
# 
#   },
# 
#   error = function(e){
# 
#     cat("Error:", e$message, "\n")
# 
#     return(NULL)
# 
#   })
# 
# }

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# air_data <- clean_variable(air_data, "PM2.5")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# comparison_table <- data.frame(
# 
#   Variable = c(numeric_variables, "wd"),
# 
#   Missing_Before = c(before_missing, before_wd),
# 
#   Missing_After = c(after_missing, after_wd)
# 
# )
# 
# comparison_table$Values_Replaced <-
# comparison_table$Missing_Before -
# comparison_table$Missing_After
# 
# print(comparison_table)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# before_after <- rbind(
#   comparison_table$Missing_Before,
#   comparison_table$Missing_After
# )
# 
# colnames(before_after) <- comparison_table$Variable
# 
# barplot(
#   before_after,
#   beside = TRUE,
#   col = c("red", "green"),
#   names.arg = comparison_table$Variable,
#   main = "Missing Values Before and After Cleaning",
#   xlab = "Variables",
#   ylab = "Number of Missing Values",
#   legend.text = c("Before", "After")
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# write.csv(
#   air_data,
#   "cleaned_air_quality.csv",
#   row.names = FALSE
# )
# 
# cat("Cleaned dataset saved successfully!\n")